### ISSUE TITLE
Dashboard and Minecraft Server crash together, only one works

### ISSUE THREAD

**Issue by joernKoenen** [benbaptist/wrapper.py#11]
Hey,
my Issue is that I can't run the dashboard and the minecraft server at the same time. Only one is able to run.
If I disable the dashboard the mc server works but if I enable it, it instantly crashes while trying to launch. The Dashboard itself works fine.

I'm running it on a VPS and I had a similar Issue with PaperMC without Wrapper. It would always crash after a while and say "unable to create native thread: possibly out of memory or process/resource limits". I came to the conclusion that it has to do with my Host who limits the number of threads using beancounters (numproc is set to 400). I now run the vanilla jar and that works.

I think my Issue with the Dashboard is that SocketIO or Flask creates too many threads. Do you have an idea how to decrease the number of threads? I don't think it's a problem with ram because I have 8gb and no other programs running. I could provide the javacore and heapdump error files if those help.

Another question is, what does the cmd option do in the config file? Could I set it to "java -Xmx1024M -Xms1024M -jar minecraft_server.1.16.4.jar nogui" for example, and it would use that command to start the server?

I know that you are not tech support and understand if you can't or don't want to help me.

Greetings

![Untitled](https://user-images.githubusercontent.com/45468633/104602749-05501580-567c-11eb-8634-a7b017f71fe8.png)

**Comment by joernKoenen** [comment]
Okay, I may have solved my Issue. I changed threads=32 in /dashboard/__init__.py Line 90 to threads=1. It seems to work fine for now.

**Comment by benbaptist** [comment]
No worries, I'm always welcome.to help out! Weird that changing thread count fixed it. I'll have to do a little more digging to find out why. But I should probably add a setting to configure thread count for now (or somehow determine the appropriate amount of threads).

As for the cmd property, yup, it is basically an override for the internal command generator. So any server jar/RAM/etc. settings in the rest of the config or on the dashboard become useless.

**Comment by benbaptist** [comment]
I didn't really think straight while reading the post, so that does indeed make sense why the thread count was causing issues. I believe I had to override the fancy asynchronous stuff and make it basic threads because of some weird intermittent issues, so if I can figure those issues out, it would be way better on thread count.

**Comment by joernKoenen** [comment]
Alright, thanks for your help!
The only drawback of threads=1 I saw yet is that the website is a bit slower because requests have to wait in the queue.

Another question is, what do the scripts in the config do? Is a given script executed if the event happens and if so what should one write instead of the "null"?
Also, it's normal that "Dashboard" and "Scripts" return 404 right? I guess they are not implemented yet.

And I'm happy to report that my first plugin works. I just had to figure out that a command starts with a dot haha. Writing ".day" now sets the time to 0.

**Comment by benbaptist** [comment]
No problem! 

For the scripts, those are just basic event-called scripts, and you'd set them to the path of the script. I believe some of them (`backup-finished`, or whatveier it's called) get some arguments passed on, like the backup file location. Definitely going to need to make more documentation on this. 

Indeed, Dashboard and Scripts are just simply unimplememted at this point. Probably wouldn't hurt to me to throw an "under construction!" page up for those tabs for now.

That's awesome, glad to hear it's working!
