### ISSUE TITLE
Doesn't work with Paper

### ISSUE THREAD

**Issue by joernKoenen** [benbaptist/wrapper.py#13]
Hey, it's me again.

I moved to a new VPS and can now run papermc. But sadly I noticed that wrapper.py doesn't work with papermc. The server starts like usual, wrapper opens the website and loads plugins, but the plugins don't work (No player joined message, etc.).

I think wrapper can't interact with the console (read or write).

Stopping the server also doesn't work (I have to write wrapper stop in terminal and /stop ingame to stop it). The terminal prints only one error when starting the server: [main/warn] advanced terminal features are not available in this environment
Adding "-Dterminal.jline=false -Dterminal.ansi=true" to the start-options fixed the error but the issues still exist.

I tried Vanilla 1.16.4 and 5 and PaperMC 1.16.4 and 5. Both Vanilla versions work and both paper versions don't.

I found these Issues which may be related to this one:
https://github.com/PaperMC/Paper/issues/2257
https://github.com/PaperMC/Paper/pull/2299
https://github.com/jline/jline3/issues/411

Greetings

**Comment by benbaptist** [comment]
Ahh, interesting! I’ll have to run some tests once I get home and see what’s going on. I suspect it’s outputting its line output on STDERR or something, instead of STDOUT (or vice versa, I can’t remember what the vanilla server outputs at the moment).

**Comment by benbaptist** [comment]
Looks like it was just a simple parsing issue. Got it resolved in the next commit to the development branch!

**Comment by joernKoenen** [comment]
Awesome, thanks a lot!

**Comment by benbaptist** [comment]
My pleasure!
