### ISSUE TITLE
plugins load but do not function.

### ISSUE THREAD

**Issue by l33tlinuxh4x0r** [benbaptist/wrapper.py#8]
I can get the test plugin to load, however I cannot run any of the test commands. Am I missing something. I remember that the old version of the wrapper needed a proxy mode. Is that still a thing? If so how do I use it?

**Comment by benbaptist** [comment]
So, in this new Wrapper, there's no proxy mode implememted yet - instead, custom commands can are ran by sending messages starting with the command prefix as defined in `wrapper-data/config.json`, which defaults to "."

e.g.
`.getpos`

Of course, once proxy mode is implemented, it'll be possible to use normal `/command` commands

**Comment by benbaptist** [comment]
Should be functional; feel free to re-oepn if you're still having issues.
